export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_TEST = "LOGIN_TEST";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_TEST = "REGISTER_TEST";

export const EMAIL_VALIDATE = "EMAIL_VALIDATE"
export const EMAIL_VALIDATE_CHECKED = "EMAIL_VALIDATE_CHECKED"

export const PRICE_LOADING = "PRICE_LOADING";
export const PRICE_SUCCESS = "PRICE_SUCCESS";
export const PRICE_ERROR = "PRICE_ERROR";

export const CHECK_ADDRESS_LOADING = "CHECK_ADDRESS_LOADING";
export const CHECK_ADDRESS_SUCCESS = "CHECK_ADDRESS_SUCCESS";
export const CHECK_ADDRESS_ERROR = "CHECK_ADDRESS_ERROR";

export const AUTO_FEE_LOADING = "AUTO_FEE_LOADING";
export const AUTO_FEE_SUCCESS = "AUTO_FEE_SUCCESS";
export const AUTO_FEE_ERROR = "AUTO_FEE_ERROR";