export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_TEST = "LOGIN_TEST";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_TEST = "REGISTER_TEST";

export const EMAIL_VALIDATE = "EMAIL_VALIDATE"
export const EMAIL_VALIDATE_CHECKED = "EMAIL_VALIDATE_CHECKED"

export const PRICE_LOADING = "PRICE_LOADING";
export const PRICE_SUCCESS = "PRICE_SUCCESS";
export const PRICE_ERROR = "PRICE_ERROR";

export const CHECK_ADDRESS_LOADING = "CHECK_ADDRESS_LOADING";
export const CHECK_ADDRESS_SUCCESS = "CHECK_ADDRESS_SUCCESS";
export const CHECK_ADDRESS_ERROR = "CHECK_ADDRESS_ERROR";

export const AUTO_FEE_LOADING = "AUTO_FEE_LOADING";
export const AUTO_FEE_SUCCESS = "AUTO_FEE_SUCCESS";
export const AUTO_FEE_ERROR = "AUTO_FEE_ERROR";

export const USER_DETAILS_LOADING = "USER_DETAILS_LOADING";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_ERROR = "USER_DETAILS_ERROR";

export const SEND_COIN_LOADING = "SEND_COIN_LOADING";
export const SEND_COIN_SUCCESS = "SEND_COIN_SUCCESS";
export const SEND_COIN_ERROR = "SEND_COIN_ERROR";

export const GET_NOTIFICATION_LOADING = "GET_NOTIFICATION_LOADING";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_ERROR = "GET_NOTIFICATION_ERROR";

export const VALIDATE_ACCOUNT_LOADING = "VALIDATE_ACCOUNT_LOADING";
export const VALIDATE_ACCOUNT_SUCCESS = "VALIDATE_ACCOUNT_SUCCESS";
export const VALIDATE_ACCOUNT_ERROR = "VALIDATE_ACCOUNT_ERROR";

export const ID_CARD_LOADING = "ID_CARD_LOADING";
export const ID_CARD_SUCCESS = "ID_CARD_SUCCESS";
export const ID_CARD_ERROR = "ID_CARD_ERROR";