import {MdOutlineSecurity} from 'react-icons/md'
import '../../../../assets/css/Modal/modal.css'
const Index = ({Next})=>{
    return(
        <div>
            <div className='welcome2fa-section slide-right'>
                    
                
                <p>
                    Enabling this feature means that every time you try to log into your Jupit account, both your password and your 2FA code are required to access your account or allow funds to be transferred from your account.
                </p>
                <p>
                    Please read the instructions carefully as we will guide you step by step to enable this feature.
                </p>
                <p>
                    1. Download and install an authenticator from the App Store or Google Play Store on your mobile phone device (preferably Google Authenticator app).
                </p>
                <p>
                    2. Scan the QR code below from the authentication app already installed on your mobile device, or copy the secret key to manually paste it into the authentication app for setup.
                </p>
                <p>
                    3. Enter the token generated by the authenticator to verify and enable this feature.
                </p>

                <div className='TabInput SubmitModal' onClick={()=>Next('Section3')} >
                    Enable 2FA  
                </div>
            </div>

            
        </div>
    )
}
export default Index;